[project]
name = "try"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyunderstand",
]

[tool.uv.sources]
pyunderstand = { git = "https://github.com/kaihendry/pyunderstand2" }
